### ISSUE TITLE
[Roadmap] Further Optimaztion

### ISSUE THREAD

**Issue by LukeLIN-web** [LukeLIN-web/gnnproject#2]
### Priority1
* [ ] Data parallel, cache one hop neighbor feature on the GPU, if NVLink clique has this feature, we don’t store replica. 
* [ ] use big graph.  MAG有59,000,000个node,TWeibo也很大  ,**DGraphFin**也大. https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.datasets.AttributedGraphDataset.html#torch_geometric.datasets.AttributedGraphDataset  
* [x] 先计算出哪些会重用. 然后cache这些node的中间结果. 
* [ ] cache a part of input feature ， Choose highest degree input feature. 
* [ ] use `trim_layer`  In PyG ，可以先得到node然后用subgraph。loader , 可以用subgraph,   用loader之后, 就可以用khop subgrpah了 。  k_hop_subgraph 非常慢, 因为要调用unique函数, 用trim layer.新建每个Data类也非常费时, CPU处理了, 转移到GPU也很费时. 
* [ ] 需要处理get nano batch没有出边的情况. 
* [ ] use neighbor-loader in PyG.  
* [ ]  use nvshmem
* [ ] 不同的nano batch, 可以分到异构GPU上. 
* [ ] get micro batch 改成 cpp代码.  很困难,  torch函数有cpp libtorch。
* [ ] Support full batch training.
* [ ] 利用H100 的系统。 Grace Hopper, has faster CPU-GPU connection. 480GB/s. GPU has 95GB memory.
* [ ] 考虑load balancing， 先完成的多分几个nanobatch。 多GPU的时候, 测试速度. 我们还没有尝试多GPU, 可能会有更好的性能? 因为我们只用sample一次.  原来的方案每个GPU都需要sample.  或者用nvshmem. 考虑load balancing， 先完成的多分几个nanobatch。 
* [ ] The idea is to reduce the cache feature amount. For example, PCIe 3.0 has a transfer rate of 16GB/s to the GPU. We assume the time to transfer 2GB or 1.5GB features would be the same. So caching 90% of node features or 80% of node features would result in similar transfer times. Our initial step involves comparing the performance differences of different caches for a batch and measuring the latency of transferring features of various sizes to the GPU. 

### 速度慢的原因
因为 每个nano batch 的大小是不固定的, 所以非常多index select操作.  prune慢, 因为要选择对应id,   pull慢, 搜索id慢.
